services:
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    restart: always
    env_file: .env
    ports:
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - ${DOCKER_NETWORK_NAME:-innonetwork}
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server kafka:29092" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-secret}
    env_file: .env
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ${DOCKER_NETWORK_NAME:-innonetwork}
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    env_file: .env
    ports:
      - "${API_GATEWAY_PORT:-8080}:8080"
    environment:
      SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME:-inno-api-gateway}
      SERVER_PORT: ${SERVER_PORT:-8080}
      HEADER_USER_ID: ${HEADER_USER_ID:-X-User-Id}
      CONTENT_TYPE_JSON: ${CONTENT_TYPE_JSON:-application/json}
      USER_SERVICE_URI: ${USER_SERVICE_URI}
      ORDER_SERVICE_URI: ${ORDER_SERVICE_URI}
      PAYMENT_SERVICE_URI: ${PAYMENT_SERVICE_URI}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${KEYCLOAK_ISSUER_URI}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      RANDOM_API_BASE_URL: ${RANDOM_API_BASE_URL}
      SWAGGER_KEYCLOAK_TOKEN_URL: ${SWAGGER_KEYCLOAK_TOKEN_URL}
    depends_on:
      kafka:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      user-service:
        condition: service_started
      order-service:
        condition: service_started
      payment-service:
        condition: service_started
    networks:
      - ${DOCKER_NETWORK_NAME:-innonetwork}
    restart: on-failure

  user-service:
    build:
      context: ../InnoUserService
      dockerfile: Dockerfile
    container_name: user-service
    env_file: .env
    ports:
      - "${USER_SERVICE_PORT:-8082}:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${USER_DB_HOST}:${USER_DB_PORT}/${USER_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${USER_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${USER_DB_PASSWORD}
      SPRING_REDIS_HOST: ${REDIS_HOST}
      SPRING_REDIS_PORT: ${REDIS_PORT}
      SPRING_REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      SERVER_PORT: ${USER_SERVICE_PORT:-8082}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      SWAGGER_KEYCLOAK_TOKEN_URL: ${SWAGGER_KEYCLOAK_TOKEN_URL}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${KEYCLOAK_ISSUER_URI}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
    depends_on:
      postgres_user:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - ${DOCKER_NETWORK_NAME:-innonetwork}
    restart: on-failure

  order-service:
    build:
      context: ../InnoOrderService
      dockerfile: Dockerfile
    container_name: order-service
    env_file: .env
    ports:
      - "${ORDER_SERVICE_PORT:-8086}:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${ORDER_DB_HOST}:${ORDER_DB_PORT}/${ORDER_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${ORDER_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${ORDER_DB_PASSWORD}
      SERVER_PORT: ${ORDER_SERVICE_PORT:-8086}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_ORDER_EVENTS_TOPIC: ${KAFKA_ORDER_EVENTS_TOPIC:-order-events}
      USER_SERVICE_URI: ${USER_SERVICE_URI}
      SPRING_REDIS_HOST: ${REDIS_HOST}
      SPRING_REDIS_PORT: ${REDIS_PORT}
      SWAGGER_KEYCLOAK_TOKEN_URL: ${SWAGGER_KEYCLOAK_TOKEN_URL}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${KEYCLOAK_ISSUER_URI}
      KEYCLOAK_ISSUER_URI: ${KEYCLOAK_ISSUER_URI}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      ORDER_SERVICE_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      ORDER_SERVICE_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
    depends_on:
      postgres_order:
        condition: service_healthy
      kafka:
        condition: service_healthy
      user-service:
        condition: service_started
    networks:
      - ${DOCKER_NETWORK_NAME:-innonetwork}
    restart: on-failure

  payment-service:
    build:
      context: ../InnoPaymentService
      dockerfile: Dockerfile
    container_name: payment-service
    env_file: .env
    ports:
      - "${PAYMENT_SERVICE_PORT:-8087}:8087"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME:-root}:${MONGO_INITDB_ROOT_PASSWORD:-secret}@${MONGO_HOST:-mongodb}:${MONGO_PORT:-27017}/${PAYMENT_DB_NAME:-payment_db}?authSource=admin
      SPRING_DATASOURCE_URL: jdbc:postgresql://${PAYMENT_DB_HOST}:${PAYMENT_DB_PORT}/${PAYMENT_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${PAYMENT_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${PAYMENT_DB_PASSWORD}
      SERVER_PORT: ${PAYMENT_SERVICE_PORT:-8087}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_PAYMENT_EVENTS_TOPIC: ${KAFKA_PAYMENT_EVENTS_TOPIC}
    depends_on:
      mongodb:
        condition: service_healthy
      postgres_payment:
        condition: service_healthy
      kafka:
        condition: service_healthy
      order-service:
        condition: service_started
    networks:
      - ${DOCKER_NETWORK_NAME:-innonetwork}
    restart: on-failure

  postgres_user:
    image: postgres:15
    container_name: postgres_user
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${USER_DB_USERNAME}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    env_file: .env
    ports:
      - "5434:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    networks:
      - ${DOCKER_NETWORK_NAME:-innonetwork}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USER_DB_USERNAME} -d ${USER_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  postgres_order:
    image: postgres:15
    container_name: postgres_order
    environment:
      POSTGRES_DB: ${ORDER_DB_NAME}
      POSTGRES_USER: ${ORDER_DB_USERNAME}
      POSTGRES_PASSWORD: ${ORDER_DB_PASSWORD}
    env_file: .env
    ports:
      - "5435:5432"
    volumes:
      - postgres_order_data:/var/lib/postgresql/data
    networks:
      - ${DOCKER_NETWORK_NAME:-innonetwork}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${ORDER_DB_USERNAME} -d ${ORDER_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  postgres_payment:
    image: postgres:15
    container_name: postgres_payment
    environment:
      POSTGRES_DB: ${PAYMENT_DB_NAME}
      POSTGRES_USER: ${PAYMENT_DB_USERNAME}
      POSTGRES_PASSWORD: ${PAYMENT_DB_PASSWORD}
    env_file: .env
    ports:
      - "5436:5432"
    volumes:
      - postgres_payment_data:/var/lib/postgresql/data
    networks:
      - ${DOCKER_NETWORK_NAME:-innonetwork}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PAYMENT_DB_USERNAME} -d ${PAYMENT_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis
    env_file: .env
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - ${DOCKER_NETWORK_NAME:-innonetwork}
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  minikube:
    image: gcr.io/k8s-minikube/kicbase:v0.0.42
    container_name: minikube
    privileged: true
    restart: always
    ports:
      - "8443:8443"
      - "2376:2376"
      - "5000:5000"
      - "32443:32443"
    environment:
      MINIKUBE_IN_DOCKER: "true"
    volumes:
      - minikube_data:/var/lib/minikube
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ${DOCKER_NETWORK_NAME:-innonetwork}

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    restart: always
    env_file: .env
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      # KC_DB: postgres
      # KC_DB_URL: jdbc:postgresql://postgres_keycloak:5432/keycloak
      # KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME:-keycloak}
      # KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-keycloak}
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      #      KC_HOSTNAME: localhost
      #      KC_HOSTNAME_PORT: ${KEYCLOAK_PORT:-8088}
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    ports:
      - "${KEYCLOAK_PORT:-8088}:8080"
    volumes:
      - ./keycloak/realm-config:/opt/keycloak/data/import:ro
    command: [ "start-dev", "--import-realm", "--optimized" ]
    depends_on:
      postgres_keycloak:
        condition: service_healthy
    networks:
      - ${DOCKER_NETWORK_NAME:-innonetwork}
    healthcheck:
      test: [ "CMD", "bash", "-c", "exec 3<>/dev/tcp/127.0.0.1/9000 && echo -e 'GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && cat <&3 | grep 'HTTP/1.1 200 OK' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  postgres_keycloak:
    image: postgres:15
    container_name: postgres_keycloak
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME:-keycloak}
      POSTGRES_USER: ${KEYCLOAK_DB_USERNAME:-keycloak}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-keycloak}
    env_file: .env
    ports:
      - "${KEYCLOAK_DB_PORT:-5437}:5432"
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    networks:
      - ${DOCKER_NETWORK_NAME:-innonetwork}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${KEYCLOAK_DB_USERNAME:-keycloak} -d ${KEYCLOAK_DB_NAME:-keycloak}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "${PROMETHEUS_PORT:-9091}:9091"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'
      - '--web.listen-address=:9091'
    networks:
      - ${DOCKER_NETWORK_NAME:-innonetwork}
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9091/-/healthy" ]
      interval: 10s
      timeout: 5s
      retries: 5

  loki:
    image: grafana/loki:latest
    container_name: loki
    user: "root"
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki/loki-config.yml:/etc/loki/local-config.yaml
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - ${DOCKER_NETWORK_NAME:-innonetwork}

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    user: "root"
    restart: always
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"
    volumes:
      - ./monitoring/tempo/tempo.yml:/etc/tempo.yaml
      - tempo_data:/tmp/tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    networks:
      - ${DOCKER_NETWORK_NAME:-innonetwork}

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    networks:
      - ${DOCKER_NETWORK_NAME:-innonetwork}
    depends_on:
      prometheus:
        condition: service_healthy
      loki:
        condition: service_started
      tempo:
        condition: service_started
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  innonetwork:
    driver: bridge
    name: ${DOCKER_NETWORK_NAME:-innonetwork}

volumes:
  postgres_user_data:
  postgres_order_data:
  postgres_payment_data:
  postgres_keycloak_data:
  kafka_data:
  mongo_data:
  minikube_data:
  redis_data:
  prometheus_data:
  loki_data:
  tempo_data:
  grafana_data:
