spring:
  application:
    name: ${SPRING_APPLICATION_NAME:inno-api-gateway}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/innowise-realm}

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URI:http://user-service:8082}
          predicates:
            - Path=/api/users/**,/api/cards/**

        - id: order-service
          uri: ${ORDER_SERVICE_URI:http://order-service:8086}
          predicates:
            - Path=/api/orders/**,/api/items/**,/api/order-items/**

        - id: user-service-swagger
          uri: ${USER_SERVICE_URI:http://user-service:8082}
          predicates:
            - Path=/user-service/v3/api-docs/**
          filters:
            - RewritePath=/user-service/(?<path>.*), /$\{path}

        - id: order-service-swagger
          uri: ${ORDER_SERVICE_URI:http://order-service:8086}
          predicates:
            - Path=/order-service/v3/api-docs/**
          filters:
            - RewritePath=/order-service/(?<path>.*), /$\{path}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: User Service
        url: /user-service/v3/api-docs
      - name: Order Service
        url: /order-service/v3/api-docs
    config-parameters:
      usePkceWithAuthorizationCodeGrant: true
      clientId: innowise-client
      appName: Innowise Gateway
    oauth:
      clientId: innowise-client
      appName: Innowise Gateway
      use-pkce-with-authorization-code-grant: true
    display-request-duration: true
  api-docs:
    path: /v3/api-docs


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  prometheus:
    metrics:
      export:
        enabled: true
  observations:
    key-values:
      application: ${spring.application.name}
      service: api-gateway
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${TEMPO_ENDPOINT:http://tempo:4318/v1/traces}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
