spring:
  application:
    name: ${SPRING_APPLICATION_NAME:inno-api-gateway}

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URI:http://auth-service:8081}
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: ${USER_SERVICE_URI:http://user-service:8082}
          predicates:
            - Path=/api/users/**
            - Path=/api/cards/**

        - id: order-service
          uri: ${ORDER_SERVICE_URI:http://order-service:8086}
          predicates:
            - Path=/api/orders/**
            - Path=/api/items/**
            - Path=/api/order-items/**

        - id: auth-service-swagger
          uri: ${AUTH_SERVICE_URI:http://auth-service:8081}
          predicates:
            - Path=/auth-service/v3/api-docs/**
          filters:
            - RewritePath=/auth-service/(?<path>.*), /$\{path}

        - id: user-service-swagger
          uri: ${USER_SERVICE_URI:http://user-service:8082}
          predicates:
            - Path=/user-service/v3/api-docs/**
          filters:
            - RewritePath=/user-service/(?<path>.*), /$\{path}

        - id: order-service-swagger
          uri: ${ORDER_SERVICE_URI:http://order-service:8086}
          predicates:
            - Path=/order-service/v3/api-docs/**
          filters:
            - RewritePath=/order-service/(?<path>.*), /$\{path}

        - id: payment-service-swagger
          uri: ${PAYMENT_SERVICE_URI:http://payment-service:8087}
          predicates:
            - Path=/payment-service/v3/api-docs/**
          filters:
            - RewritePath=/payment-service/(?<path>.*), /$\{path}

jwt:
  secret: ${JWT_SECRET}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Auth Service
        url: /auth-service/v3/api-docs
      - name: User Service
        url: /user-service/v3/api-docs
      - name: Order Service
        url: /order-service/v3/api-docs
      - name: Payment Service
        url: /payment-service/v3/api-docs
  api-docs:
    path: /v3/api-docs


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  prometheus:
    metrics:
      export:
        enabled: true
  observations:
    key-values:
      application: ${spring.application.name}
      service: api-gateway
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${TEMPO_ENDPOINT:http://tempo:4318/v1/traces}
